### ISSUE TITLE
No such file or directory: 'sudo /usr/bin/terracli'

### ISSUE THREAD

**Issue by alecande11** [b-harvest/terra_oracle_voter#28]
Whien I run `systemctl start oracle` i got this error:

```
● oracle.service - Terra Oracle
     Loaded: loaded (/etc/systemd/system/oracle.service; disabled; vendor preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Fri 2020-10-30 12:23:40 CET; 352ms ago
    Process: 27222 ExecStart=/usr/bin/python3 -u ~/terra_oracle_voter/terra_oracle_vote.py (code=exited, status=217/USER)
   Main PID: 27222 (code=exited, status=217/USER)

Oct 30 12:23:40 VPS001 systemd[1]: oracle.service: Main process exited, code=exited, status=217/USER
Oct 30 12:23:40 VPS001 systemd[1]: oracle.service: Failed with result 'exit-code'.
```

So I tryed to run `python3 terra_oracle_vote.py` and I got this error:

```
INFO:root:360694: wait 1.0 blocks until this round ends...
ERROR:root:Error in get_fx_rate
Traceback (most recent call last):
  File "terra_oracle_vote.py", line 340, in get_fx_rate
    api_result[list_number]["Realtime Currency Exchange Rate"]["5. Exchange Rate"])
KeyError: 'Realtime Currency Exchange Rate'
INFO:root:Active set: ['uusd', 'ukrw', 'usdr', 'umnt']
INFO:root:Prevoting uusd : 0.30417889744729815(percent_change:-0.0800%)
INFO:root:Prevoting ukrw : 344.6969567396699(percent_change:-0.1313%)
INFO:root:Prevoting usdr : 0.21539824964782237(percent_change:-0.2183%)
INFO:root:Prevoting umnt : 867.9894724548534(percent_change:0.0239%)
INFO:root:Start voting on height 360696
INFO:root:Broadcast prevotes only...
INFO:root:Prevoting...
INFO:root:Signing...
Traceback (most recent call last):
  File "terra_oracle_vote.py", line 1087, in <module>
    broadcast_prevote(this_hash)
  File "terra_oracle_vote.py", line 717, in broadcast_prevote
    return broadcast_messages([
  File "terra_oracle_vote.py", line 688, in broadcast_messages
    cmd_output = subprocess.check_output([
  File "/usr/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'sudo /usr/bin/terracli'
```

if I run `sudo /usr/bin/terracli` terracli start

**Comment by nodebreaker0-0** [comment]
This is a permission/path issue for sudo
Assuming that the "terracli" you want to run is in "/home/{server username}/go" or "/home/{server username}/goApps"

Edit the "sudo nano /etc/sudoures" file

`Defaults secure_path="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/home/{server username}/go/bin"`
